AppMensajes/urls.py
from django.urls import path, include, re_path

from .views import DerailMs, CanalDetailView, Inbox, busquedaUsuarios
	
#"c66cde68-bf1a-4965-9be4-09438daf0482" este es un ejemplo de un codigo de id que se generan automaticamente, siempre tienen la misma cantidad de caracteres entre guiones
#el codigo de abajo es una manera de recuperar los codigos id de los canales de mensajeria, [a-f0-9]{8}, indica que hay 8 caracteres entre letras y numeros, el -? indica que hay un guion y que si se quita alguno de los numeros o letras de cada cadena no se rompe la pagina solo nos tira error de que no existe ese canal
UUID_CANAL_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'


urlpatterns=[

	re_path(UUID_CANAL_REGEX, CanalDetailView.as_view()),
	
	path("MensajeDirecto/<str:username>", DerailMs.as_view(), name="detailms"),
    path("Applocal/", include("Applocal.urls")),
	path("busquedaUsuarios/", busquedaUsuarios, name="busquedausuarios"),
	
	path("inbox/", Inbox.as_view(), name="inbox"),
	



]

Applocal/urls.py
from django.urls import path
from Applocal.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("post/", post, name="post"),
    path("miPerfil/", miPerfil, name="miPerfil"),

    path("login/", login_request, name='login'),
    path("register/", register, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("editarPerfil/", editarPerfil, name="editarPerfil"),
    path("editarPost/", editarPost, name="editarPost"),
    path("AgregarAvatar/", AgregarAvatar, name="AgregarAvatar"),
]

proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from Applocal.views import inicio
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Applocal/", include("Applocal.urls")),
    path("AppMensajes/", include("AppMensajes.urls")),
    path("", inicio, name="inicio"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppMensajes/models.py
from django.db import models
from django.conf import settings
import uuid

from django.apps import apps

from django.db.models import Count

User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False) #id unica universal creada con shell "319118fa-8987-432d-b59d-ef004026445d"
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)



class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False #el false es para no crearlo en la BD

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)  #aca filtramos si hay una conversacion si la hay lo devuelve
		if qs.exists():

			return qs.order_by("tiempo").first(), False #devuelve el objeto si fue creado o no



		User = apps.get_model("auth", model_name="User")
		usuario_a, usuario_b = None, None

		try:
			usuario_a = User.objects.get(username=username_a)
		except User.DoesNotExist:
			return None, False

		try:
			usuario_b = User.objects.get(username=username_b)
		except User.DoesNotExist:
			return None, False

		if usuario_a == None or usuario_b == None:
			return None, False


		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=usuario_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=usuario_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b]) #bulk es un metodo de administrador de objetos usando una matriz
		return obj_canal, True



class Canal(ModelBase):
	
	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)
	objects = CanalManager()

AppMensajes/forms.py
from django import forms

class FormMensajes(forms.Form):
    mensaje = forms.CharField(widget=forms.Textarea(attrs = {
            
            "class": "formulario_ms", 
            "placeholder": "Escribe tu mensaje",
            "cols" : "50",
            "rows": "4",

        }))

AppMensajes/views.py
from django.shortcuts import render

from django.views.generic import DetailView

from .models import CanalMensaje, Canal
from django.http import Http404

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from .forms import FormMensajes
from django.views.generic.edit import FormMixin

from django.views.generic import View

from Applocal.models import Avatar

from django.contrib.auth import get_user_model






class Inbox(View):
	def get(self, request):
		
		lista=Avatar.objects.filter(user=request.user)
		if len(lista)!=0:
			imagen=lista[0].imagen.url
		else:
			imagen=None

		inbox = Canal.objects.filter(canalusuario__usuario__in=[request.user.id])


		context = {

			"imagen":imagen,
			"inbox":inbox,
	
		}
			

		return render(request, 'inbox.html', context)


class CanalFormMixin(FormMixin):
	form_class =FormMensajes

	def get_success_url(self):
		return self.request.path

	def post(self, request, *args, **kwargs):

		if not request.user.is_authenticated:
			raise PermissionDenied

		form = self.get_form()
		if form.is_valid():
			canal = self.get_object()
			usuario = self.request.user 
			mensaje = form.cleaned_data.get("mensaje")
			canal_obj = CanalMensaje.objects.create(canal=canal, usuario=usuario, texto=mensaje)
			return super().form_valid(form)
		else:
			return super().form_invalid(form)
			


class CanalDetailView(LoginRequiredMixin, CanalFormMixin, DetailView):
	template_name="canal_detail.html"
	queryset = Canal.objects.all()
	

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)


		obj = context['object']
		print(obj)

		context['si_canal_miembro'] = self.request.user in obj.usuarios.all()
		return context
	
	

class DerailMs(LoginRequiredMixin, CanalFormMixin, DetailView):  #Detail de mensajes

	template_name="canal_detail.html"

	def get_object(self, *args, **kwargs):

		username = self.kwargs.get("username")
		mi_username = self.request.user.username
		canal, _ = Canal.objects.obtener_o_crear_canal_ms(mi_username, username)

		if username == mi_username:
			mi_canal, _ = Canal.objects.obtener_o_crear_canal_usuario_actual(self.request.user)

			return mi_canal

		if canal == None:
			raise Http404

		return canal


	#para crear un canal nuevo necesito poner el request: http://127.0.0.1:8000/AppMensajes/MensajeDirecto/Paco

	#necesito un formulario que me muestre los nombres de que esten logeados
	#cuando elija uno puedo clickear sobre el y me crea el chat devolviendo "Appmensajes/MensajeDirecto/Paco"


def busquedaUsuarios(request):

		User = get_user_model()
		usuarios = User.objects.all()
		
		return render(request, "busquedaUsuarios.html", {"usuarios":usuarios})

AppMensajes/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %} 

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mensajes Directos</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />   
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'inicio' %}">CoderBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'inicio' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'about' %}">Acerca de mi</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contact' %}">Contact</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'miPerfil' %}" style="background-color:rgb(64, 70, 63)"><img src="{{ imagen }}" alt="" width="auto" height="23px"> {{ user.username }}</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'inbox' %}">Sala de chats</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Cerrar sesión</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">Ingresar</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-1 justify-content-center">
            
                    <div class="site-heading">
                        {% block titulo %}

                        {% endblock %}
                        <span class="subheading">
                            {% block subtitulo %}

                            {% endblock %}
                        </span>
                    </div>
                
            </div>
        </div>
    </header>




    <div>
        {% block contenedor %}
            
        {% endblock %}
    </div>




    
    
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/toto_mls">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/toto.silva.16/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/MauroLeonelSilva">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Mauro Silva 2022</div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

AppMensajes/templates/busquedaUsuarios.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
<h1>usuarios en CoderBlog</h1>
{% endblock %}

{% block subtitulo %}
<p>haz click en el usuario con el que quieras iniciar una conversación</p>
{% endblock %}


{% block contenedor %}

<div style=" display: flex; flex-direction: row;justify-content: space-around; background-color: rgb(61, 95, 158); ">
{% for usuarios in usuarios %}
            <a href="../MensajeDirecto/{{ usuarios }}">
                <p style="color: white;">{{ usuarios }}</p>
            </a>
            
            {% endfor %}
        </div>



{% endblock %}

AppMensajes/templates/canal_detail.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}

{% for second_user in object.canalusuario_set.all %}
    {% if second_user.usuario == request.user %}
    {% else %}
    
        <h1>
            chat con {{second_user.usuario}} {{ imagen }}
        </h1>
    
    {% endif %}
{% endfor %}

{% endblock %}

{% block contenedor %}






<div id="externo" style="width: 100%;
height: calc(70vh);
margin: 5px 0;
overflow-y: auto;
border-bottom: 1px solid #e6e6e6;
background: #fff;">
    <div id="interno" class="container px-4 px-lg-5">
    

        <div>
            {% for mensaje in object.canalmensaje_set.all %}
            
            {% if request.user == mensaje.usuario %}
                <p>
                <span>
                    <strong>Tú</strong>
                </span>
                <small>({{mensaje.tiempo}}):</small>
                </p>
                <p>
                    {{mensaje.texto}}
                </p>
            {% else %}
                <p>
                    <span>
                        <strong>{{mensaje.usuario}} -</strong>
                    </span>
                    <small>({{mensaje.tiempo}}):</small>
                </p>
                    <p>
                        {{mensaje.texto}}
                    </p>
                        {% endif %}

            {% endfor %}
        </div>

        </div>

</div>

<div style="width: 100%;
            margin-top: 5px;
            margin-bottom: 5px;
            margin-left: 5px;
            border:1px solid #e6e6e6;">

            <div style= "margin-left: 10em;">
                <form action="{{ request.path }}" method="POST">
                    {% csrf_token %}
                
                    {{form.as_p}}
        
                    <div style= "text-align: center">
                        <button type="submit">
                            Enviar
                        </button>
                    </div>
                </form>

            </div>
    
    </div>



{% endblock %}

AppMensajes/templates/inbox.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<h2>Bienvenido {{user}} a tu sala de chats</h2>
{% endblock %}

{% block subtitulo %}
<p>haz click en el usuario con el que quieras hablar, o crea un chat nuevo</p>
{% endblock %}

{% block contenedor %}
{% for inbox in inbox %}

<div >

    
    {% for second_user in inbox.canalusuario_set.all %}
    
    {% if second_user.usuario == request.user %}
    
    {% else %}
    <div style=" text-align: center; border-style: ridge;">
        
        <a href="{% url 'detailms' second_user.usuario.username %}">
            <p >
                chat con {{second_user.usuario}}
            </p>
        </a>
    </div>
    
            {% endif %}
    
        {% endfor %}
    
        {% if inbox.canalmensaje_set.count == 0 %}
                <p>
                    no hay mensajes en nuestro inbox
                </p>
        {% endif %}
    
        {% empty %}
        
        <h3 style="display: flex; justify-content: center;">
            no tienes mensajes :(
        </h3>
        {% endfor %}
        
        <div style="padding: 10px 0; text-align: center; border-style: ridge;"> 
            <a href="../busquedaUsuarios">
                <h4>crear un chat nuevo</h4>
            </a>
        </div>
        
    </div>
    {% endblock %}